server:
  port: 8080

spring:
  profiles:
    active: dev

  application:
    name: book-library-api

  datasource:
    url:
    username: root
    password:

  data:
    mongodb:
      uri:

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
