server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/book_library?useSSL=false'
    username: root
    password: 123456

  data:
    mongodb:
      uri: mongodb://longvh:123456@127.0.0.1:27017/book_library

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        user-topic-input:
          binder: kafka
          destination: user-topic
          contentType: text/json
          group: user-input-group-1
        user-topic-output:
          binder: kafka
          destination: user-topic
          contentType: text/json
          group: user-output-group-1


management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - httptrace
async:
  thread:
    pool:
      core-size: 2
      max-size: 2
      queue-capacity: 100

security:
  jwt:
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: ^$JwtSecretKey@
