version: "3"

networks:
  mysql:
    driver: bridge

services:
  mysql:
    container_name: "mysqldb"
    networks:
      - mysql
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - e:/mysql-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=db_wr
      - MYSQL_PASSWORD=123456

  phpmyadmin:
    container_name: "myphpmyadmin"
    networks:
      - mysql
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8082:80"
    restart: always
    environment:
      - PMA_HOST=mysqldb
    depends_on:
      - mysql

  mongodb:
    container_name: "mongodb"
    image: "mongo"
    restart: always
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongodata:/data/db

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis-master:
    image: bitnami/redis
    environment:
      REDIS_REPLICATION_MODE: master
      #REDIS_PASSWORD: 1q2w3e4r
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    volumes:
      - redis_data_master:/bitnami

  redis-slave:
    image: bitnami/redis
    depends_on: [redis-master]
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master
      #REDIS_MASTER_PASSWORD: 1q2w3e4r
      #REDIS_PASSWORD: 1q2w3e4r
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6380-6382:6379"
    volumes:
      - redis_data_slave:/bitnami

  redis-sentinel:
    image: bitnami/redis-sentinel
    depends_on: [redis-master]
    volumes:
      - redis-sentinel_data:/bitnami
    ports:
      - "26379-26382:26379"
    environment:
      REDIS_MASTER_HOST: localhost
      #REDIS_MASTER_PASSWORD: 1q2w3e4r

volumes:
  redis_data_master:
    driver: local
  redis_data_slave:
    driver: local
  redis-sentinel_data:
    driver: local
  mongodata:
